theme = "ayu_dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
idle-timeout = 0
completion-trigger-len = 1
true-color = true

[editor.indent-guides]
render = true
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false